exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - '.jekyll-cache'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/Helsinki
encoding: utf-8
lang: en-US
title: "Public DNS resolvers"
description: "Find the IP addresses of public resolvers easilly."
url: "https://resolvers.samip.dev"
baseurl: ""
repo: "https://github.com/samip5/resolvers-page"
date_format: "%d.%m.%Y"
css_inline: true
destination: ./_site

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
